[package]
name = "bday"
description = "Yet another discord bot (yadb | bday)"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = { git = "https://github.com/serenity-rs/poise", branch = "current", features = ["collector"] }
tokio = { version = "1.39.2", features = ["process", "rt-multi-thread"] }
